name: Build Compatibility
on: [ push ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Swift Version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Get Swift Version
        run: swift --version

      - name: Checkout Package
        uses: actions/checkout@v4

      - name: Build Package
        run: swift build

      - name: Test Package
        run: swift test